import { LabRequest } from '@/types/labRequest';
import { DeliveryRequest } from '@/types/deliveryRequest';

export const sampleLabRequests: Omit<LabRequest, 'id' | 'createdAt'>[] = [
  {
    potentialId: 'POT-2025-001',
    freshDeskTicketNumber: 'FD-45678',
    month: 'February',
    year: 2025,
    client: 'Acme Corporation',
    cloud: 'AWS',
    labName: 'Kubernetes Fundamentals',
    requester: 'John Smith',
    agentName: 'Sarah Johnson',
    accountManager: 'Mike Wilson',
    receivedOn: '2025-01-15',
    labStartDate: '2025-02-01',
    labEndDate: '2025-02-05',
    userCount: 25,
    durationInDays: 5,
    inputCostPerUser: 150,
    sellingCostPerUser: 250,
    totalAmountForTraining: 18750,
    margin: 18750 - (25 * 5 * 150),
    status: 'Solution Sent',
    remarks: 'Client requested additional Docker modules',
  },
  {
    potentialId: 'POT-2025-002',
    freshDeskTicketNumber: 'FD-45892',
    month: 'February',
    year: 2025,
    client: 'TechStart Inc',
    cloud: 'Azure',
    labName: 'Azure DevOps Workshop',
    requester: 'Emily Chen',
    agentName: 'David Brown',
    accountManager: 'Lisa Taylor',
    receivedOn: '2025-01-20',
    labStartDate: '2025-02-10',
    labEndDate: '2025-02-12',
    userCount: 15,
    durationInDays: 3,
    inputCostPerUser: 200,
    sellingCostPerUser: 350,
    totalAmountForTraining: 9000,
    margin: 9000 - (15 * 3 * 200),
    status: 'Solution Pending',
    remarks: 'Awaiting confirmation on lab environment specs',
  },
  {
    potentialId: 'POT-2025-003',
    freshDeskTicketNumber: 'FD-46123',
    month: 'March',
    year: 2025,
    client: 'GlobalTech Solutions',
    cloud: 'GCP',
    labName: 'Google Cloud Architect',
    requester: 'Robert Garcia',
    agentName: 'Amanda White',
    accountManager: 'James Lee',
    receivedOn: '2025-02-10',
    labStartDate: '2025-03-05',
    labEndDate: '2025-03-08',
    userCount: 20,
    durationInDays: 4,
    inputCostPerUser: 180,
    sellingCostPerUser: 320,
    totalAmountForTraining: 12800,
    margin: 12800 - (20 * 4 * 180),
    status: 'Solution Sent',
    remarks: 'Priority client - expedited setup required',
  },
  {
    potentialId: 'POT-2025-004',
    freshDeskTicketNumber: 'FD-46234',
    month: 'March',
    year: 2025,
    client: 'FinServe Bank',
    cloud: 'AWS',
    labName: 'AWS Security Essentials',
    requester: 'Priya Sharma',
    agentName: 'Carlos Rodriguez',
    accountManager: 'Mike Wilson',
    receivedOn: '2025-02-15',
    labStartDate: '2025-03-12',
    labEndDate: '2025-03-14',
    userCount: 30,
    durationInDays: 3,
    inputCostPerUser: 220,
    sellingCostPerUser: 400,
    totalAmountForTraining: 18600,
    margin: 18600 - (30 * 3 * 220),
    status: 'Solution Sent',
    remarks: 'Banking compliance requirements included',
  },
  {
    potentialId: 'POT-2025-005',
    freshDeskTicketNumber: 'FD-46345',
    month: 'April',
    year: 2025,
    client: 'HealthCare Plus',
    cloud: 'Azure',
    labName: 'Azure Data Engineering',
    requester: 'Jennifer Adams',
    agentName: 'Sarah Johnson',
    accountManager: 'Lisa Taylor',
    receivedOn: '2025-03-01',
    labStartDate: '2025-04-02',
    labEndDate: '2025-04-06',
    userCount: 18,
    durationInDays: 5,
    inputCostPerUser: 250,
    sellingCostPerUser: 450,
    totalAmountForTraining: 16200,
    margin: 16200 - (18 * 5 * 250),
    status: 'Solution Pending',
    remarks: 'HIPAA compliant environment needed',
  },
  {
    potentialId: 'POT-2025-006',
    freshDeskTicketNumber: 'FD-46456',
    month: 'April',
    year: 2025,
    client: 'RetailMax Corp',
    cloud: 'GCP',
    labName: 'BigQuery Analytics',
    requester: 'Michael Turner',
    agentName: 'Amanda White',
    accountManager: 'James Lee',
    receivedOn: '2025-03-10',
    labStartDate: '2025-04-15',
    labEndDate: '2025-04-17',
    userCount: 22,
    durationInDays: 3,
    inputCostPerUser: 190,
    sellingCostPerUser: 340,
    totalAmountForTraining: 11660,
    margin: 11660 - (22 * 3 * 190),
    status: 'Solution Sent',
    remarks: 'E-commerce data integration focus',
  },
  {
    potentialId: 'POT-2025-007',
    freshDeskTicketNumber: 'FD-46567',
    month: 'May',
    year: 2025,
    client: 'EduTech Academy',
    cloud: 'AWS',
    labName: 'Machine Learning on AWS',
    requester: 'David Kim',
    agentName: 'Carlos Rodriguez',
    accountManager: 'Mike Wilson',
    receivedOn: '2025-04-05',
    labStartDate: '2025-05-01',
    labEndDate: '2025-05-05',
    userCount: 35,
    durationInDays: 5,
    inputCostPerUser: 280,
    sellingCostPerUser: 500,
    totalAmountForTraining: 27300,
    margin: 27300 - (35 * 5 * 280),
    status: 'Solution Sent',
    remarks: 'SageMaker and Bedrock modules included',
  },
  // 2026 data
  {
    potentialId: 'POT-2026-001',
    freshDeskTicketNumber: 'FD-50001',
    month: 'January',
    year: 2026,
    client: 'FutureTech Labs',
    cloud: 'AWS',
    labName: 'AWS Lambda Advanced',
    requester: 'Alex Turner',
    agentName: 'David Brown',
    accountManager: 'Mike Wilson',
    receivedOn: '2025-12-15',
    labStartDate: '2026-01-10',
    labEndDate: '2026-01-14',
    userCount: 28,
    durationInDays: 5,
    inputCostPerUser: 200,
    sellingCostPerUser: 380,
    totalAmountForTraining: 21280,
    margin: 21280 - (28 * 5 * 200),
    status: 'Solution Sent',
    remarks: 'Serverless architecture focus',
  },
  {
    potentialId: 'POT-2026-002',
    freshDeskTicketNumber: 'FD-50002',
    month: 'January',
    year: 2026,
    client: 'DataDriven Co',
    cloud: 'GCP',
    labName: 'Vertex AI Workshop',
    requester: 'Maria Santos',
    agentName: 'Sarah Johnson',
    accountManager: 'Lisa Taylor',
    receivedOn: '2025-12-20',
    labStartDate: '2026-01-20',
    labEndDate: '2026-01-23',
    userCount: 20,
    durationInDays: 4,
    inputCostPerUser: 300,
    sellingCostPerUser: 520,
    totalAmountForTraining: 16400,
    margin: 16400 - (20 * 4 * 300),
    status: 'Solution Pending',
    remarks: 'AI/ML advanced training',
  },
  {
    potentialId: 'POT-2026-003',
    freshDeskTicketNumber: 'FD-50003',
    month: 'February',
    year: 2026,
    client: 'SecureNet Inc',
    cloud: 'Azure',
    labName: 'Azure Security Center',
    requester: 'James Wilson',
    agentName: 'Carlos Rodriguez',
    accountManager: 'James Lee',
    receivedOn: '2026-01-05',
    labStartDate: '2026-02-05',
    labEndDate: '2026-02-08',
    userCount: 32,
    durationInDays: 4,
    inputCostPerUser: 240,
    sellingCostPerUser: 420,
    totalAmountForTraining: 21120,
    margin: 21120 - (32 * 4 * 240),
    status: 'Solution Sent',
    remarks: 'Zero trust security model',
  },
];

export const sampleDeliveryRequests: Omit<DeliveryRequest, 'id' | 'createdAt'>[] = [
  {
    potentialId: 'POT-2025-001',
    freshDeskTicketNumber: 'FD-45678',
    trainingName: 'Kubernetes Fundamentals',
    numberOfUsers: 25,
    month: 'February',
    year: 2025,
    receivedOn: '2025-01-15',
    client: 'Acme Corporation',
    cloud: 'AWS',
    labName: 'K8s-Lab-Acme',
    requester: 'John Smith',
    agentName: 'Sarah Johnson',
    accountManager: 'Mike Wilson',
    labStatus: 'Ready',
    labType: 'Cloud',
    startDate: '2025-02-01',
    endDate: '2025-02-05',
    labSetupRequirement: 'Hardware: 16GB RAM, 8 Core CPU, 200GB Storage\nSoftware: Docker, Kubernetes, Helm\nVersion: K8s 1.28, Docker 24.0, Helm 3.x',
    inputCostPerUser: 150,
    sellingCostPerUser: 250,
    totalAmount: 25 * (150 + 250),
  },
  {
    potentialId: 'POT-2025-003',
    freshDeskTicketNumber: 'FD-46001',
    trainingName: 'Terraform Infrastructure',
    numberOfUsers: 20,
    month: 'February',
    year: 2025,
    receivedOn: '2025-01-25',
    client: 'GlobalTech Solutions',
    cloud: 'GCP',
    labName: 'TF-Lab-Global',
    requester: 'Robert Garcia',
    agentName: 'Amanda White',
    accountManager: 'James Lee',
    labStatus: 'In Progress',
    labType: 'Hybrid',
    startDate: '2025-02-15',
    endDate: '2025-02-18',
    labSetupRequirement: 'Hardware: 8GB RAM, 4 Core CPU, 100GB Storage\nSoftware: Terraform, GCloud CLI\nVersion: Terraform 1.6, GCloud SDK latest',
    inputCostPerUser: 180,
    sellingCostPerUser: 300,
    totalAmount: 20 * (180 + 300),
  },
  {
    potentialId: 'POT-2025-004',
    freshDeskTicketNumber: 'FD-46234',
    trainingName: 'AWS Security Essentials',
    numberOfUsers: 30,
    month: 'March',
    year: 2025,
    receivedOn: '2025-02-15',
    client: 'FinServe Bank',
    cloud: 'AWS',
    labName: 'AWS-Sec-FinServe',
    requester: 'Priya Sharma',
    agentName: 'Carlos Rodriguez',
    accountManager: 'Mike Wilson',
    labStatus: 'Completed',
    labType: 'Cloud',
    startDate: '2025-03-12',
    endDate: '2025-03-14',
    labSetupRequirement: 'Hardware: 32GB RAM, 16 Core CPU, 500GB Storage\nSoftware: AWS CLI, Security Hub, GuardDuty\nVersion: Latest AWS tools',
    inputCostPerUser: 220,
    sellingCostPerUser: 400,
    totalAmount: 30 * (220 + 400),
  },
  {
    potentialId: 'POT-2025-005',
    freshDeskTicketNumber: 'FD-46345',
    trainingName: 'Azure Data Engineering',
    numberOfUsers: 18,
    month: 'April',
    year: 2025,
    receivedOn: '2025-03-01',
    client: 'HealthCare Plus',
    cloud: 'Azure',
    labName: 'Azure-DE-Health',
    requester: 'Jennifer Adams',
    agentName: 'Sarah Johnson',
    accountManager: 'Lisa Taylor',
    labStatus: 'Ready',
    labType: 'Cloud',
    startDate: '2025-04-02',
    endDate: '2025-04-06',
    labSetupRequirement: 'Hardware: 64GB RAM, 32 Core CPU, 1TB Storage\nSoftware: Azure Data Factory, Synapse, Databricks\nVersion: Latest Azure services',
    inputCostPerUser: 250,
    sellingCostPerUser: 450,
    totalAmount: 18 * (250 + 450),
  },
  {
    potentialId: 'POT-2025-006',
    freshDeskTicketNumber: 'FD-46456',
    trainingName: 'BigQuery Analytics',
    numberOfUsers: 22,
    month: 'April',
    year: 2025,
    receivedOn: '2025-03-10',
    client: 'RetailMax Corp',
    cloud: 'GCP',
    labName: 'BQ-Lab-Retail',
    requester: 'Michael Turner',
    agentName: 'Amanda White',
    accountManager: 'James Lee',
    labStatus: 'In Progress',
    labType: 'Cloud',
    startDate: '2025-04-15',
    endDate: '2025-04-17',
    labSetupRequirement: 'Hardware: 16GB RAM, 8 Core CPU, 200GB Storage\nSoftware: BigQuery, Looker, Data Studio\nVersion: GCP latest',
    inputCostPerUser: 190,
    sellingCostPerUser: 340,
    totalAmount: 22 * (190 + 340),
  },
  {
    potentialId: 'POT-2025-007',
    freshDeskTicketNumber: 'FD-46567',
    trainingName: 'Machine Learning on AWS',
    numberOfUsers: 35,
    month: 'May',
    year: 2025,
    receivedOn: '2025-04-05',
    client: 'EduTech Academy',
    cloud: 'AWS',
    labName: 'ML-Lab-EduTech',
    requester: 'David Kim',
    agentName: 'Carlos Rodriguez',
    accountManager: 'Mike Wilson',
    labStatus: 'Pending',
    labType: 'Cloud',
    startDate: '2025-05-01',
    endDate: '2025-05-05',
    labSetupRequirement: 'Hardware: 128GB RAM, 64 Core CPU, 2TB Storage, GPU instances\nSoftware: SageMaker, Bedrock, Python 3.11\nVersion: Latest ML frameworks',
    inputCostPerUser: 280,
    sellingCostPerUser: 500,
    totalAmount: 35 * (280 + 500),
  },
  {
    potentialId: 'POT-2025-008',
    freshDeskTicketNumber: 'FD-46678',
    trainingName: 'Docker Containerization',
    numberOfUsers: 28,
    month: 'May',
    year: 2025,
    receivedOn: '2025-04-12',
    client: 'StartupHub Inc',
    cloud: 'AWS',
    labName: 'Docker-Lab-Startup',
    requester: 'Emily Chen',
    agentName: 'David Brown',
    accountManager: 'Lisa Taylor',
    labStatus: 'Ready',
    labType: 'Hybrid',
    startDate: '2025-05-10',
    endDate: '2025-05-12',
    labSetupRequirement: 'Hardware: 16GB RAM, 8 Core CPU, 300GB Storage\nSoftware: Docker, Docker Compose, Portainer\nVersion: Docker 24.0',
    inputCostPerUser: 160,
    sellingCostPerUser: 290,
    totalAmount: 28 * (160 + 290),
  },
  // 2026 data
  {
    potentialId: 'POT-2026-001',
    freshDeskTicketNumber: 'FD-50001',
    trainingName: 'AWS Lambda Advanced',
    numberOfUsers: 28,
    month: 'January',
    year: 2026,
    receivedOn: '2025-12-15',
    client: 'FutureTech Labs',
    cloud: 'AWS',
    labName: 'Lambda-Lab-Future',
    requester: 'Alex Turner',
    agentName: 'David Brown',
    accountManager: 'Mike Wilson',
    labStatus: 'Ready',
    labType: 'Cloud',
    startDate: '2026-01-10',
    endDate: '2026-01-14',
    labSetupRequirement: 'Hardware: 16GB RAM, 8 Core CPU, 200GB Storage\nSoftware: AWS CLI, SAM, Lambda Layers\nVersion: Node.js 20, Python 3.12',
    inputCostPerUser: 200,
    sellingCostPerUser: 380,
    totalAmount: 28 * (200 + 380),
  },
  {
    potentialId: 'POT-2026-002',
    freshDeskTicketNumber: 'FD-50002',
    trainingName: 'Vertex AI Workshop',
    numberOfUsers: 20,
    month: 'January',
    year: 2026,
    receivedOn: '2025-12-20',
    client: 'DataDriven Co',
    cloud: 'GCP',
    labName: 'VertexAI-Lab-Data',
    requester: 'Maria Santos',
    agentName: 'Sarah Johnson',
    accountManager: 'Lisa Taylor',
    labStatus: 'In Progress',
    labType: 'Cloud',
    startDate: '2026-01-20',
    endDate: '2026-01-23',
    labSetupRequirement: 'Hardware: 64GB RAM, 32 Core CPU, 1TB Storage, TPU\nSoftware: Vertex AI, TensorFlow, PyTorch\nVersion: Latest GCP ML tools',
    inputCostPerUser: 300,
    sellingCostPerUser: 520,
    totalAmount: 20 * (300 + 520),
  },
  {
    potentialId: 'POT-2026-003',
    freshDeskTicketNumber: 'FD-50003',
    trainingName: 'Azure Security Center',
    numberOfUsers: 32,
    month: 'February',
    year: 2026,
    receivedOn: '2026-01-05',
    client: 'SecureNet Inc',
    cloud: 'Azure',
    labName: 'AzSec-Lab-Secure',
    requester: 'James Wilson',
    agentName: 'Carlos Rodriguez',
    accountManager: 'James Lee',
    labStatus: 'Completed',
    labType: 'Cloud',
    startDate: '2026-02-05',
    endDate: '2026-02-08',
    labSetupRequirement: 'Hardware: 32GB RAM, 16 Core CPU, 500GB Storage\nSoftware: Azure Security Center, Sentinel, Defender\nVersion: Latest Azure security tools',
    inputCostPerUser: 240,
    sellingCostPerUser: 420,
    totalAmount: 32 * (240 + 420),
  },
];
