import { LabRequest } from '@/types/labRequest';

// Sample lab requests for dashboard testing
// Covers multiple months, clients, agents, statuses
export const sampleLabRequestsForSeeding: Omit<LabRequest, 'id' | 'createdAt'>[] = [
  // January 2025
  {
    potentialId: 'POT-2025-001',
    freshDeskTicketNumber: 'FD-10001',
    month: 'January',
    year: 2025,
    client: 'TechCorp Solutions',
    cloud: 'Public Cloud',
    cloudType: 'AWS',
    tpLabType: '',
    labName: 'AWS Solutions Architect Training',
    requester: 'John Smith',
    agentName: 'Ravi Kumar',
    accountManager: 'Sarah Johnson',
    receivedOn: '2025-01-05',
    labStartDate: '2025-01-15',
    labEndDate: '2025-01-20',
    userCount: 25,
    durationInDays: 5,
    inputCostPerUser: 3500,
    sellingCostPerUser: 5000,
    totalAmountForTraining: 125000,
    margin: 37500,
    status: 'Solution Sent',
    remarks: 'Successfully delivered',
    lineOfBusiness: 'VILT',
    invoiceDetails: 'INV-2025-001',
    assignedTo: null,
  },
  {
    potentialId: 'POT-2025-002',
    freshDeskTicketNumber: 'FD-10002',
    month: 'January',
    year: 2025,
    client: 'Global Finance Ltd',
    cloud: 'Private Cloud',
    cloudType: 'Azure',
    tpLabType: '',
    labName: 'Azure DevOps Fundamentals',
    requester: 'Michael Brown',
    agentName: 'Priya Sharma',
    accountManager: 'David Wilson',
    receivedOn: '2025-01-10',
    labStartDate: '2025-01-22',
    labEndDate: '2025-01-25',
    userCount: 15,
    durationInDays: 3,
    inputCostPerUser: 4000,
    sellingCostPerUser: 6000,
    totalAmountForTraining: 90000,
    margin: 30000,
    status: 'Solution Sent',
    remarks: 'Client satisfied',
    lineOfBusiness: 'Standalone',
    invoiceDetails: 'INV-2025-002',
    assignedTo: null,
  },
  
  // February 2025
  {
    potentialId: 'POT-2025-003',
    freshDeskTicketNumber: 'FD-10003',
    month: 'February',
    year: 2025,
    client: 'HealthTech Inc',
    cloud: 'Public Cloud',
    cloudType: 'GCP',
    tpLabType: '',
    labName: 'Google Cloud Platform Essentials',
    requester: 'Emily Davis',
    agentName: 'Amit Patel',
    accountManager: 'Sarah Johnson',
    receivedOn: '2025-02-01',
    labStartDate: '2025-02-10',
    labEndDate: '2025-02-14',
    userCount: 20,
    durationInDays: 4,
    inputCostPerUser: 3800,
    sellingCostPerUser: 5500,
    totalAmountForTraining: 110000,
    margin: 34000,
    status: 'Solution Sent',
    remarks: 'Completed on schedule',
    lineOfBusiness: 'VILT',
    invoiceDetails: 'INV-2025-003',
    assignedTo: null,
  },
  {
    potentialId: 'POT-2025-004',
    freshDeskTicketNumber: 'FD-10004',
    month: 'February',
    year: 2025,
    client: 'RetailMax Corp',
    cloud: 'TP Labs',
    cloudType: '',
    tpLabType: 'SAP',
    labName: 'SAP S/4HANA Implementation',
    requester: 'Robert Chen',
    agentName: 'Ravi Kumar',
    accountManager: 'David Wilson',
    receivedOn: '2025-02-05',
    labStartDate: '2025-02-18',
    labEndDate: '2025-02-28',
    userCount: 30,
    durationInDays: 10,
    inputCostPerUser: 8000,
    sellingCostPerUser: 12000,
    totalAmountForTraining: 360000,
    margin: 120000,
    status: 'Solution Sent',
    remarks: 'Large enterprise project',
    lineOfBusiness: 'Integrated',
    invoiceDetails: 'INV-2025-004',
    assignedTo: null,
  },
  {
    potentialId: 'POT-2025-005',
    freshDeskTicketNumber: 'FD-10005',
    month: 'February',
    year: 2025,
    client: 'EduLearn Academy',
    cloud: 'Public Cloud',
    cloudType: 'AWS',
    tpLabType: '',
    labName: 'AWS Machine Learning Specialty',
    requester: 'Lisa Wang',
    agentName: 'Priya Sharma',
    accountManager: 'Sarah Johnson',
    receivedOn: '2025-02-12',
    labStartDate: '2025-02-25',
    labEndDate: '2025-02-28',
    userCount: 18,
    durationInDays: 3,
    inputCostPerUser: 5000,
    sellingCostPerUser: 7500,
    totalAmountForTraining: 135000,
    margin: 45000,
    status: 'Solution Pending',
    remarks: 'Awaiting final confirmation',
    lineOfBusiness: 'VILT',
    invoiceDetails: '',
    assignedTo: null,
  },
  
  // March 2025
  {
    potentialId: 'POT-2025-006',
    freshDeskTicketNumber: 'FD-10006',
    month: 'March',
    year: 2025,
    client: 'TechCorp Solutions',
    cloud: 'Private Cloud',
    cloudType: 'Azure',
    tpLabType: '',
    labName: 'Azure Security Operations',
    requester: 'John Smith',
    agentName: 'Amit Patel',
    accountManager: 'Sarah Johnson',
    receivedOn: '2025-03-01',
    labStartDate: '2025-03-12',
    labEndDate: '2025-03-16',
    userCount: 22,
    durationInDays: 4,
    inputCostPerUser: 4200,
    sellingCostPerUser: 6300,
    totalAmountForTraining: 138600,
    margin: 46200,
    status: 'Solution Sent',
    remarks: 'Repeat customer',
    lineOfBusiness: 'Standalone',
    invoiceDetails: 'INV-2025-006',
    assignedTo: null,
  },
  {
    potentialId: 'POT-2025-007',
    freshDeskTicketNumber: 'FD-10007',
    month: 'March',
    year: 2025,
    client: 'Manufacturing Plus',
    cloud: 'TP Labs',
    cloudType: '',
    tpLabType: 'Oracle',
    labName: 'Oracle ERP Cloud Training',
    requester: 'James Miller',
    agentName: 'Ravi Kumar',
    accountManager: 'David Wilson',
    receivedOn: '2025-03-05',
    labStartDate: '2025-03-20',
    labEndDate: '2025-03-27',
    userCount: 28,
    durationInDays: 7,
    inputCostPerUser: 6500,
    sellingCostPerUser: 9500,
    totalAmountForTraining: 266000,
    margin: 84000,
    status: 'Solution Pending',
    remarks: 'Pending client approval',
    lineOfBusiness: 'Integrated',
    invoiceDetails: '',
    assignedTo: null,
  },
  
  // April 2025
  {
    potentialId: 'POT-2025-008',
    freshDeskTicketNumber: 'FD-10008',
    month: 'April',
    year: 2025,
    client: 'Global Finance Ltd',
    cloud: 'Public Cloud',
    cloudType: 'AWS',
    tpLabType: '',
    labName: 'AWS Database Specialty',
    requester: 'Michael Brown',
    agentName: 'Priya Sharma',
    accountManager: 'David Wilson',
    receivedOn: '2025-04-02',
    labStartDate: '2025-04-15',
    labEndDate: '2025-04-18',
    userCount: 16,
    durationInDays: 3,
    inputCostPerUser: 4500,
    sellingCostPerUser: 6800,
    totalAmountForTraining: 108800,
    margin: 36800,
    status: 'Solution Sent',
    remarks: 'Completed successfully',
    lineOfBusiness: 'VILT',
    invoiceDetails: 'INV-2025-008',
    assignedTo: null,
  },
  {
    potentialId: 'POT-2025-009',
    freshDeskTicketNumber: 'FD-10009',
    month: 'April',
    year: 2025,
    client: 'StartupHub',
    cloud: 'Public Cloud',
    cloudType: 'GCP',
    tpLabType: '',
    labName: 'GCP Data Engineering',
    requester: 'Alex Turner',
    agentName: 'Amit Patel',
    accountManager: 'Sarah Johnson',
    receivedOn: '2025-04-10',
    labStartDate: '2025-04-22',
    labEndDate: '2025-04-26',
    userCount: 12,
    durationInDays: 4,
    inputCostPerUser: 5200,
    sellingCostPerUser: 7800,
    totalAmountForTraining: 93600,
    margin: 31200,
    status: 'Solution Pending',
    remarks: 'New customer onboarding',
    lineOfBusiness: 'Standalone',
    invoiceDetails: '',
    assignedTo: null,
  },
  
  // May 2025
  {
    potentialId: 'POT-2025-010',
    freshDeskTicketNumber: 'FD-10010',
    month: 'May',
    year: 2025,
    client: 'HealthTech Inc',
    cloud: 'Private Cloud',
    cloudType: 'Azure',
    tpLabType: '',
    labName: 'Azure AI Fundamentals',
    requester: 'Emily Davis',
    agentName: 'Ravi Kumar',
    accountManager: 'Sarah Johnson',
    receivedOn: '2025-05-01',
    labStartDate: '2025-05-12',
    labEndDate: '2025-05-15',
    userCount: 24,
    durationInDays: 3,
    inputCostPerUser: 3600,
    sellingCostPerUser: 5400,
    totalAmountForTraining: 129600,
    margin: 43200,
    status: 'Solution Sent',
    remarks: 'Excellent feedback',
    lineOfBusiness: 'VILT',
    invoiceDetails: 'INV-2025-010',
    assignedTo: null,
  },
  {
    potentialId: 'POT-2025-011',
    freshDeskTicketNumber: 'FD-10011',
    month: 'May',
    year: 2025,
    client: 'RetailMax Corp',
    cloud: 'TP Labs',
    cloudType: '',
    tpLabType: 'SAP',
    labName: 'SAP Analytics Cloud',
    requester: 'Robert Chen',
    agentName: 'Priya Sharma',
    accountManager: 'David Wilson',
    receivedOn: '2025-05-08',
    labStartDate: '2025-05-20',
    labEndDate: '2025-05-24',
    userCount: 20,
    durationInDays: 4,
    inputCostPerUser: 7000,
    sellingCostPerUser: 10500,
    totalAmountForTraining: 210000,
    margin: 70000,
    status: 'Solution Sent',
    remarks: 'Follow-up from previous training',
    lineOfBusiness: 'Integrated',
    invoiceDetails: 'INV-2025-011',
    assignedTo: null,
  },
  
  // June 2025
  {
    potentialId: 'POT-2025-012',
    freshDeskTicketNumber: 'FD-10012',
    month: 'June',
    year: 2025,
    client: 'EduLearn Academy',
    cloud: 'Public Cloud',
    cloudType: 'AWS',
    tpLabType: '',
    labName: 'AWS Security Specialty',
    requester: 'Lisa Wang',
    agentName: 'Amit Patel',
    accountManager: 'Sarah Johnson',
    receivedOn: '2025-06-01',
    labStartDate: '2025-06-10',
    labEndDate: '2025-06-14',
    userCount: 15,
    durationInDays: 4,
    inputCostPerUser: 4800,
    sellingCostPerUser: 7200,
    totalAmountForTraining: 108000,
    margin: 36000,
    status: 'Solution Pending',
    remarks: 'Scheduling in progress',
    lineOfBusiness: 'VILT',
    invoiceDetails: '',
    assignedTo: null,
  },
  {
    potentialId: 'POT-2025-013',
    freshDeskTicketNumber: 'FD-10013',
    month: 'June',
    year: 2025,
    client: 'Manufacturing Plus',
    cloud: 'Private Cloud',
    cloudType: 'Azure',
    tpLabType: '',
    labName: 'Azure Administrator',
    requester: 'James Miller',
    agentName: 'Ravi Kumar',
    accountManager: 'David Wilson',
    receivedOn: '2025-06-05',
    labStartDate: '2025-06-18',
    labEndDate: '2025-06-22',
    userCount: 18,
    durationInDays: 4,
    inputCostPerUser: 4000,
    sellingCostPerUser: 6000,
    totalAmountForTraining: 108000,
    margin: 36000,
    status: 'Solution Sent',
    remarks: 'Admin certification track',
    lineOfBusiness: 'Standalone',
    invoiceDetails: 'INV-2025-013',
    assignedTo: null,
  },
  
  // July-December 2025 (additional records for trends)
  {
    potentialId: 'POT-2025-014',
    freshDeskTicketNumber: 'FD-10014',
    month: 'July',
    year: 2025,
    client: 'TechCorp Solutions',
    cloud: 'Public Cloud',
    cloudType: 'GCP',
    tpLabType: '',
    labName: 'GCP Professional Architect',
    requester: 'John Smith',
    agentName: 'Priya Sharma',
    accountManager: 'Sarah Johnson',
    receivedOn: '2025-07-01',
    labStartDate: '2025-07-15',
    labEndDate: '2025-07-19',
    userCount: 20,
    durationInDays: 4,
    inputCostPerUser: 5500,
    sellingCostPerUser: 8200,
    totalAmountForTraining: 164000,
    margin: 54000,
    status: 'Solution Pending',
    remarks: 'Premium certification',
    lineOfBusiness: 'VILT',
    invoiceDetails: '',
    assignedTo: null,
  },
  {
    potentialId: 'POT-2025-015',
    freshDeskTicketNumber: 'FD-10015',
    month: 'August',
    year: 2025,
    client: 'Global Finance Ltd',
    cloud: 'TP Labs',
    cloudType: '',
    tpLabType: 'OEM',
    labName: 'Microsoft Dynamics 365',
    requester: 'Michael Brown',
    agentName: 'Amit Patel',
    accountManager: 'David Wilson',
    receivedOn: '2025-08-02',
    labStartDate: '2025-08-12',
    labEndDate: '2025-08-20',
    userCount: 25,
    durationInDays: 8,
    inputCostPerUser: 6000,
    sellingCostPerUser: 9000,
    totalAmountForTraining: 225000,
    margin: 75000,
    status: 'Solution Pending',
    remarks: 'Enterprise rollout',
    lineOfBusiness: 'Integrated',
    invoiceDetails: '',
    assignedTo: null,
  },
  {
    potentialId: 'POT-2025-016',
    freshDeskTicketNumber: 'FD-10016',
    month: 'September',
    year: 2025,
    client: 'HealthTech Inc',
    cloud: 'Public Cloud',
    cloudType: 'AWS',
    tpLabType: '',
    labName: 'AWS Cloud Practitioner',
    requester: 'Emily Davis',
    agentName: 'Ravi Kumar',
    accountManager: 'Sarah Johnson',
    receivedOn: '2025-09-01',
    labStartDate: '2025-09-10',
    labEndDate: '2025-09-12',
    userCount: 40,
    durationInDays: 2,
    inputCostPerUser: 2500,
    sellingCostPerUser: 3800,
    totalAmountForTraining: 152000,
    margin: 52000,
    status: 'Solution Pending',
    remarks: 'Large batch training',
    lineOfBusiness: 'VILT',
    invoiceDetails: '',
    assignedTo: null,
  },
  {
    potentialId: 'POT-2025-017',
    freshDeskTicketNumber: 'FD-10017',
    month: 'October',
    year: 2025,
    client: 'StartupHub',
    cloud: 'Private Cloud',
    cloudType: 'Azure',
    tpLabType: '',
    labName: 'Azure DevOps Engineer',
    requester: 'Alex Turner',
    agentName: 'Priya Sharma',
    accountManager: 'Sarah Johnson',
    receivedOn: '2025-10-01',
    labStartDate: '2025-10-15',
    labEndDate: '2025-10-18',
    userCount: 14,
    durationInDays: 3,
    inputCostPerUser: 4200,
    sellingCostPerUser: 6300,
    totalAmountForTraining: 88200,
    margin: 29400,
    status: 'Solution Pending',
    remarks: 'DevOps transformation',
    lineOfBusiness: 'Standalone',
    invoiceDetails: '',
    assignedTo: null,
  },
  {
    potentialId: 'POT-2025-018',
    freshDeskTicketNumber: 'FD-10018',
    month: 'November',
    year: 2025,
    client: 'RetailMax Corp',
    cloud: 'Public Cloud',
    cloudType: 'AWS',
    tpLabType: '',
    labName: 'AWS Solutions Architect Pro',
    requester: 'Robert Chen',
    agentName: 'Amit Patel',
    accountManager: 'David Wilson',
    receivedOn: '2025-11-01',
    labStartDate: '2025-11-12',
    labEndDate: '2025-11-16',
    userCount: 12,
    durationInDays: 4,
    inputCostPerUser: 6500,
    sellingCostPerUser: 9800,
    totalAmountForTraining: 117600,
    margin: 39600,
    status: 'Solution Pending',
    remarks: 'Advanced certification',
    lineOfBusiness: 'VILT',
    invoiceDetails: '',
    assignedTo: null,
  },
  {
    potentialId: 'POT-2025-019',
    freshDeskTicketNumber: 'FD-10019',
    month: 'December',
    year: 2025,
    client: 'TechCorp Solutions',
    cloud: 'TP Labs',
    cloudType: '',
    tpLabType: 'SAP',
    labName: 'SAP BTP Developer',
    requester: 'John Smith',
    agentName: 'Ravi Kumar',
    accountManager: 'Sarah Johnson',
    receivedOn: '2025-12-01',
    labStartDate: '2025-12-10',
    labEndDate: '2025-12-18',
    userCount: 22,
    durationInDays: 8,
    inputCostPerUser: 7500,
    sellingCostPerUser: 11000,
    totalAmountForTraining: 242000,
    margin: 77000,
    status: 'Solution Pending',
    remarks: 'Year-end training',
    lineOfBusiness: 'Integrated',
    invoiceDetails: '',
    assignedTo: null,
  },
  {
    potentialId: 'POT-2025-020',
    freshDeskTicketNumber: 'FD-10020',
    month: 'December',
    year: 2025,
    client: 'EduLearn Academy',
    cloud: 'Public Cloud',
    cloudType: 'GCP',
    tpLabType: '',
    labName: 'GCP Machine Learning Engineer',
    requester: 'Lisa Wang',
    agentName: 'Priya Sharma',
    accountManager: 'Sarah Johnson',
    receivedOn: '2025-12-05',
    labStartDate: '2025-12-15',
    labEndDate: '2025-12-20',
    userCount: 16,
    durationInDays: 5,
    inputCostPerUser: 5800,
    sellingCostPerUser: 8700,
    totalAmountForTraining: 139200,
    margin: 46400,
    status: 'Solution Pending',
    remarks: 'ML specialization',
    lineOfBusiness: 'VILT',
    invoiceDetails: '',
    assignedTo: null,
  },
];
