import { LabRequest } from '@/types/labRequest';
import { DeliveryRequest } from '@/types/deliveryRequest';

export const sampleLabRequests: Omit<LabRequest, 'id' | 'createdAt'>[] = [
  {
    potentialId: 'POT-2024-001',
    freshDeskTicketNumber: 'FD-45678',
    month: 'February',
    client: 'Acme Corporation',
    cloud: 'AWS',
    labName: 'Kubernetes Fundamentals',
    requester: 'John Smith',
    agentName: 'Sarah Johnson',
    accountManager: 'Mike Wilson',
    receivedOn: '2024-01-15',
    labStartDate: '2024-02-01',
    labEndDate: '2024-02-05',
    userCount: 25,
    durationInDays: 5,
    inputCostPerUser: 150,
    sellingCostPerUser: 250,
    totalAmountForTraining: 18750,
    margin: 18750 - (25 * 5 * 150),
    status: 'Solution Sent',
    remarks: 'Client requested additional Docker modules',
  },
  {
    potentialId: 'POT-2024-002',
    freshDeskTicketNumber: 'FD-45892',
    month: 'February',
    client: 'TechStart Inc',
    cloud: 'Azure',
    labName: 'Azure DevOps Workshop',
    requester: 'Emily Chen',
    agentName: 'David Brown',
    accountManager: 'Lisa Taylor',
    receivedOn: '2024-01-20',
    labStartDate: '2024-02-10',
    labEndDate: '2024-02-12',
    userCount: 15,
    durationInDays: 3,
    inputCostPerUser: 200,
    sellingCostPerUser: 350,
    totalAmountForTraining: 9000,
    margin: 9000 - (15 * 3 * 200),
    status: 'Solution Pending',
    remarks: 'Awaiting confirmation on lab environment specs',
  },
];

export const sampleDeliveryRequests: Omit<DeliveryRequest, 'id' | 'createdAt'>[] = [
  {
    potentialId: 'POT-2024-001',
    freshDeskTicketNumber: 'FD-45678',
    trainingName: 'Kubernetes Fundamentals',
    numberOfUsers: 25,
    client: 'Acme Corporation',
    cloud: 'AWS',
    labName: 'K8s-Lab-Acme',
    requester: 'John Smith',
    agentName: 'Sarah Johnson',
    accountManager: 'Mike Wilson',
    labStatus: 'Ready',
    labType: 'Cloud',
    startDate: '2024-02-01',
    endDate: '2024-02-05',
    labSetupRequirement: 'Hardware: 16GB RAM, 8 Core CPU, 200GB Storage\nSoftware: Docker, Kubernetes, Helm\nVersion: K8s 1.28, Docker 24.0, Helm 3.x',
    inputCostPerUser: 150,
    sellingCostPerUser: 250,
    totalAmount: 25 * (150 + 250),
  },
  {
    potentialId: 'POT-2024-003',
    freshDeskTicketNumber: 'FD-46001',
    trainingName: 'Terraform Infrastructure',
    numberOfUsers: 20,
    client: 'GlobalTech Solutions',
    cloud: 'GCP',
    labName: 'TF-Lab-Global',
    requester: 'Robert Garcia',
    agentName: 'Amanda White',
    accountManager: 'James Lee',
    labStatus: 'In Progress',
    labType: 'Hybrid',
    startDate: '2024-02-15',
    endDate: '2024-02-18',
    labSetupRequirement: 'Hardware: 8GB RAM, 4 Core CPU, 100GB Storage\nSoftware: Terraform, GCloud CLI\nVersion: Terraform 1.6, GCloud SDK latest',
    inputCostPerUser: 180,
    sellingCostPerUser: 300,
    totalAmount: 20 * (180 + 300),
  },
];
