-- Insert 50+ comprehensive technology categories
-- First, let's add categories covering all major technology areas

INSERT INTO public.lab_catalog_categories (category_id, label, display_order, is_active, icon_name, gradient_color, is_featured) VALUES
-- Featured Categories (Primary Technology Areas)
('aws', 'AWS Cloud', 1, true, 'Cloud', 'bg-gradient-to-r from-orange-500 to-yellow-500', true),
('azure', 'Microsoft Azure', 2, true, 'Cloud', 'bg-gradient-to-r from-blue-500 to-cyan-500', true),
('gcp', 'Google Cloud Platform', 3, true, 'Cloud', 'bg-gradient-to-r from-red-500 to-yellow-500', true),
('kubernetes', 'Kubernetes & Containers', 4, true, 'Container', 'bg-gradient-to-r from-blue-600 to-indigo-600', true),
('devops', 'DevOps & CI/CD', 5, true, 'GitBranch', 'bg-gradient-to-r from-purple-500 to-pink-500', true),
('ai-ml', 'AI & Machine Learning', 6, true, 'Brain', 'bg-gradient-to-r from-violet-500 to-purple-500', true),
('data-engineering', 'Data Engineering', 7, true, 'Database', 'bg-gradient-to-r from-emerald-500 to-teal-500', true),
('cybersecurity', 'Cybersecurity', 8, true, 'Shield', 'bg-gradient-to-r from-red-600 to-rose-600', true),

-- Non-Featured Categories (Specialized Areas)
('oracle-oem', 'Oracle & OEM', 10, true, 'Database', 'bg-gradient-to-r from-red-500 to-orange-500', false),
('sap-labs', 'SAP Labs', 11, true, 'Building', 'bg-gradient-to-r from-blue-500 to-indigo-500', false),
('terraform', 'Terraform & IaC', 12, true, 'Layers', 'bg-gradient-to-r from-purple-600 to-violet-600', false),
('python', 'Python Development', 13, true, 'Code2', 'bg-gradient-to-r from-yellow-500 to-green-500', false),
('java', 'Java & JVM', 14, true, 'Coffee', 'bg-gradient-to-r from-orange-600 to-red-600', false),
('dotnet', '.NET & C#', 15, true, 'Laptop', 'bg-gradient-to-r from-purple-500 to-blue-500', false),
('nodejs', 'Node.js & JavaScript', 16, true, 'Zap', 'bg-gradient-to-r from-green-500 to-lime-500', false),
('react', 'React & Frontend', 17, true, 'Atom', 'bg-gradient-to-r from-cyan-500 to-blue-500', false),
('databases', 'Database Administration', 18, true, 'Database', 'bg-gradient-to-r from-slate-500 to-gray-600', false),
('linux', 'Linux Administration', 19, true, 'Terminal', 'bg-gradient-to-r from-yellow-600 to-orange-600', false),
('windows-server', 'Windows Server', 20, true, 'Server', 'bg-gradient-to-r from-blue-400 to-blue-600', false),
('networking', 'Networking & Infrastructure', 21, true, 'Network', 'bg-gradient-to-r from-teal-500 to-cyan-500', false),
('vmware', 'VMware & Virtualization', 22, true, 'Cpu', 'bg-gradient-to-r from-blue-600 to-slate-600', false),
('openshift', 'OpenShift & Red Hat', 23, true, 'Container', 'bg-gradient-to-r from-red-500 to-red-700', false),
('ansible', 'Ansible Automation', 24, true, 'Settings', 'bg-gradient-to-r from-red-400 to-pink-500', false),
('jenkins', 'Jenkins & CI/CD', 25, true, 'GitBranch', 'bg-gradient-to-r from-red-500 to-orange-500', false),
('gitlab', 'GitLab & Version Control', 26, true, 'GitBranch', 'bg-gradient-to-r from-orange-500 to-red-500', false),
('docker', 'Docker Containerization', 27, true, 'Box', 'bg-gradient-to-r from-blue-400 to-cyan-500', false),
('microservices', 'Microservices Architecture', 28, true, 'Boxes', 'bg-gradient-to-r from-indigo-500 to-purple-500', false),
('api-development', 'API Development', 29, true, 'Link', 'bg-gradient-to-r from-green-500 to-emerald-500', false),
('mongodb', 'MongoDB & NoSQL', 30, true, 'Database', 'bg-gradient-to-r from-green-600 to-green-800', false),
('postgresql', 'PostgreSQL', 31, true, 'Database', 'bg-gradient-to-r from-blue-600 to-slate-600', false),
('mysql', 'MySQL & MariaDB', 32, true, 'Database', 'bg-gradient-to-r from-orange-500 to-blue-500', false),
('redis', 'Redis & Caching', 33, true, 'Zap', 'bg-gradient-to-r from-red-500 to-red-700', false),
('elasticsearch', 'Elasticsearch & ELK', 34, true, 'Search', 'bg-gradient-to-r from-yellow-500 to-orange-500', false),
('kafka', 'Apache Kafka', 35, true, 'Activity', 'bg-gradient-to-r from-slate-600 to-gray-800', false),
('spark', 'Apache Spark', 36, true, 'Flame', 'bg-gradient-to-r from-orange-500 to-yellow-500', false),
('hadoop', 'Hadoop & Big Data', 37, true, 'Server', 'bg-gradient-to-r from-yellow-600 to-amber-600', false),
('snowflake', 'Snowflake', 38, true, 'Snowflake', 'bg-gradient-to-r from-cyan-400 to-blue-500', false),
('databricks', 'Databricks', 39, true, 'Sparkles', 'bg-gradient-to-r from-red-500 to-orange-500', false),
('power-bi', 'Power BI & Analytics', 40, true, 'BarChart3', 'bg-gradient-to-r from-yellow-500 to-amber-500', false),
('tableau', 'Tableau Visualization', 41, true, 'PieChart', 'bg-gradient-to-r from-blue-500 to-orange-500', false),
('salesforce', 'Salesforce', 42, true, 'Cloud', 'bg-gradient-to-r from-blue-400 to-cyan-400', false),
('servicenow', 'ServiceNow', 43, true, 'Settings', 'bg-gradient-to-r from-green-500 to-teal-500', false),
('splunk', 'Splunk & Monitoring', 44, true, 'Activity', 'bg-gradient-to-r from-pink-500 to-rose-500', false),
('prometheus', 'Prometheus & Grafana', 45, true, 'LineChart', 'bg-gradient-to-r from-orange-500 to-red-500', false),
('iot', 'IoT & Edge Computing', 46, true, 'Wifi', 'bg-gradient-to-r from-teal-500 to-green-500', false),
('blockchain', 'Blockchain & Web3', 47, true, 'Link2', 'bg-gradient-to-r from-purple-500 to-indigo-500', false),
('mobile-dev', 'Mobile Development', 48, true, 'Smartphone', 'bg-gradient-to-r from-blue-500 to-violet-500', false),
('flutter', 'Flutter & Dart', 49, true, 'Smartphone', 'bg-gradient-to-r from-cyan-400 to-blue-500', false),
('golang', 'Go (Golang)', 50, true, 'Code', 'bg-gradient-to-r from-cyan-500 to-teal-500', false),
('rust', 'Rust Programming', 51, true, 'Cog', 'bg-gradient-to-r from-orange-600 to-red-600', false),
('testing-qa', 'Testing & QA', 52, true, 'CheckSquare', 'bg-gradient-to-r from-green-500 to-lime-500', false),
('selenium', 'Selenium Automation', 53, true, 'Bug', 'bg-gradient-to-r from-green-600 to-emerald-600', false),
('agile-scrum', 'Agile & Scrum', 54, true, 'Users', 'bg-gradient-to-r from-indigo-500 to-blue-500', false),
('site-reliability', 'SRE & Reliability', 55, true, 'Gauge', 'bg-gradient-to-r from-violet-500 to-purple-500', false),
('finops', 'FinOps & Cloud Cost', 56, true, 'DollarSign', 'bg-gradient-to-r from-green-500 to-emerald-500', false)
ON CONFLICT (category_id) DO UPDATE SET
  label = EXCLUDED.label,
  display_order = EXCLUDED.display_order,
  is_active = EXCLUDED.is_active,
  icon_name = EXCLUDED.icon_name,
  gradient_color = EXCLUDED.gradient_color,
  is_featured = EXCLUDED.is_featured,
  updated_at = now();